swagger: '2.0'
info:
  title: api
  description: API REST.
  version: "0.0.1"
host: localhost:8080
schemes:
  - http
basePath: /v1
produces:
  - application/json
consumes:
 - application/json
paths:
  /login:
    post:
      summary: Login.
      description: Get token after login.
      parameters:
        - name: email
          in: formData
          type: string
          required: true
        - name: password
          in: formData
          type: string
          required: true
      tags:
        - Auth
      responses:
        200:
          description: New JWT.
          schema:
            type: string
        400:
          description: Missing required parameter error.
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Unexpected error provided by backend service.
          schema:
            $ref: '#/definitions/Error'
  /signup:
    post:
      summary: Sign up.
      description: New users registration.
      parameters:
        - name: email
          in: formData
          type: string
          required: true
        - name: password
          in: formData
          type: string
          required: true
        - name: name
          in: formData
          type: string
          required: false
      tags:
        - Auth
      responses:
        200:
          description: New JWT.
          schema:
            type: string
        400:
          description: Missing required parameter error.
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Unexpected error provided by backend service.
          schema:
            $ref: '#/definitions/Error'
definitions:
  User:
    type: object
    properties:
      role:
        type: string
      profile:
        type: object
        properties:
          naem:
            type: string
          email:
            type: string
            format: email
          password:
            type: date
      api_key:
        type: string
      refresh_token:
        type: string
      last_login:
        type: date
      createdAt:
        type: date
      updatedAt:
        type: date
  Error:
    type: object
    properties:
      statusCode:
        type: integer
        format: int32
      message:
        type: string
