---
development:
  jwt:
    secret: JWT_SECRET
    expiresIn: JWT_EXPIRATION
staging:
  jwt:
    secret: JWT_SECRET
    expiresIn: JWT_EXPIRATION
production:
  jwt:
    secret: JWT_SECRET
    expiresIn: JWT_EXPIRATION