---
staging:
  port: 8085
  logFile: "./logs/stag.log"
  newsApiKey: NEWS_API_APIKEY
  jwt:
    secret: 'YOUR_SECRET'
  db:
    url: 'mongodb://localhost:27017/'
    name: 'coin-news'
  cron:
    dummyCron: '*/30 * * * *'
